### ISSUE TITLE
Shows message when component has default props

### ISSUE THREAD

**Issue by nkbt** [Aweary/react-is-deprecated#5]
When component has default props (so they are not passed from outside), react-is-deprecated still spawns deprecation message.

See https://github.com/gpbl/react-day-picker/issues/188

I reckon it would be nice to show deprecation message only when props are passed from outside, but not defined as defaultProps within the same component.

Not sure if it is technically possible to distinct those though. Feel free to close if not really.

Cheers!

**Comment by aweary** [comment]
Hey @nkbt sorry for the delay, totally forgot about this issue. As far as I know there isn't a way for this package to tell if a prop is from `defaultProps` or not. React just passes all the `props` together to these PropType validators so this would have to be addressed in the package implementing it (which it looks like it has).

I'm closing for now since I don't think I can do anything, plus a component shouldn't be passing in a default value for a prop that is deprecated anyways.
